#PBS -A open

#PBS -l nodes=1:ppn=20

#PBS -l walltime=40:00:00

#PBS -l feature=rhel7

#PBS -l pmem=2gb

#PBS -j oe

cd /gpfs/group/efc5279/default/chad/

module load anaconda3
source activate mafft

mkdir -p /gpfs/group/efc5279/default/chad/HMMER_results2/output
mkdir -p /gpfs/group/efc5279/default/chad/HMMER_results2/tables
echo “”
ouput_dir = /gpfs/group/efc5279/default/chad/HMMER_results2/output/VFOC_WITHIN_
for genomes in $(ls HIGH_QUALITY_proteins)
	do
                hmmsearch -o /gpfs/group/efc5279/default/chad/HMMER_results2/output/VFOC_WITHIN_${genomes} --cpu 19 --tblout /gpfs/group/efc5279/default/chad/HMMER_results2/tables/VFOC_WITHIN_${genomes} --notextw HMMER_HMM/VFOC.hmm HIGH_QUALITY_proteins/$genomes
    done
echo “”

source deactivate
