#PBS -A open

#PBS -l nodes=1:ppn=20

#PBS -l walltime=48:00:00

#PBS -l feature=rhel7

#PBS -l pmem=8gb

#PBS -j oe

cd /gpfs/group/efc5279/default/chad/
mkdir -p PCR_results/fasta
module load anaconda3
source activate gtdbtk-1.5.0

for f in HIGH_QUALITY_GENOMES_11-12-2021/* 
do
NAME="$(basename ${f} genomic.fna)"
if [ ! -f PCR_results/${NAME}PCR.txt ]
then
perl in_silico_PCR.pl -s ${f} -m -r -i -l 1300 -p allPSSCprimers.txt >PCR_results/${NAME}PCR.txt 2>PCR_results/fasta/${NAME}amplicons.fa
fi
done
conda deactivate
